import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import BestSeller from "@/components/BestSeller";
import LatestProductSec from "@/components/LatestProductSec";
import LatestMobiles from "@/components/LatestMobiles";
import ShopByPrice from "@/components/ShopByPrice";
import InstallmentBanner from "@/components/installmentBanner";
import Steps from "@/components/Steps";
import Product from "@/models/product";
import ProductList from "@/components/ProductList";
import Features from "@/components/Features";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title> U-Shop || Ahmad </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Features />
      <ProductList props={data} />
      <Steps />
    </>
  )
}

export async function getServerSideProps() {
  const response = await fetch(
    "https://e-commerce-frontend-zeta.vercel.app//api/get-all-product"
  );
  const data = await response.json()

  return { props: { data } }
}
